<?php

/*
 * Daftar bank untuk isian nomor rekening.
 *
 * Yang tersimpan di kolom `users.bank` adalah kodenya (kode kliring BI),
 * tetapi yang ditampilkan selalu namanya — angka "014" tidak berarti
 * apa-apa bagi orang yang mengisinya.
 */

return [
    '002' => 'BRI',
    '008' => 'BANK MANDIRI',
    '009' => 'BNI',
    '200' => 'BANK TABUNGAN NEGARA',
    '011' => 'BANK DANAMON',
    '013' => 'BANK PERMATA',
    '014' => 'BCA',
    '016' => 'MAYBANK',
    '019' => 'PANINBANK',
    '022' => 'CIMB NIAGA',
    '023' => 'BANK UOB INDONESIA',
    '028' => 'BANK OCBC NISP',
    '087' => 'BANK HSBC INDONESIA',
    '147' => 'BANK MUAMALAT',
    '153' => 'BANK SINARMAS',
    '426' => 'BANK MEGA',
    '441' => 'BANK BUKOPIN',
    '451' => 'BSI',
    '484' => 'BANK KEB HANA INDONESIA',
    '494' => 'BANK RAYA INDONESIA',
    '506' => 'BANK MEGA SYARIAH',
    '046' => 'BANK DBS INDONESIA',
    '947' => 'BANK ALADIN SYARIAH',
    '950' => 'BANK COMMONWEALTH',
    '213' => 'BANK BTPN',
    '490' => 'BANK NEO COMMERCE',
    '501' => 'BANK DIGITAL BCA',
    '521' => 'BANK BUKOPIN SYARIAH',
    '535' => 'SEABANK INDONESIA',
    '542' => 'BANK JAGO',
    '567' => 'ALLO BANK',
    '110' => 'BPD JAWA BARAT',
    '111' => 'BPD DKI',
    '112' => 'BPD DAERAH ISTIMEWA YOGYAKARTA',
    '113' => 'BPD JAWA TENGAH',
    '114' => 'BPD JAWA TIMUR',
    '115' => 'BPD JAMBI',
    '116' => 'BANK ACEH SYARIAH',
    '117' => 'BPD SUMATERA UTARA',
    '118' => 'BANK NAGARI',
    '119' => 'BPD RIAU KEPRI SYARIAH',
    '120' => 'BPD SUMATERA SELATAN DAN BANGKA BELITUNG',
    '121' => 'BPD LAMPUNG',
    '122' => 'BPD KALIMANTAN SELATAN',
    '123' => 'BPD KALIMANTAN BARAT',
    '124' => 'BPD KALIMANTAN TIMUR DAN KALIMANTAN UTARA',
    '125' => 'BPD KALIMANTAN TENGAH',
    '126' => 'BPD SULAWESI SELATAN DAN SULAWESI BARAT',
    '127' => 'BPD SULAWESI UTARA DAN GORONTALO',
    '128' => 'BANK NTB SYARIAH',
    '129' => 'BPD BALI',
    '130' => 'BPD NUSA TENGGARA TIMUR',
    '131' => 'BPD MALUKU DAN MALUKU UTARA',
    '132' => 'BPD PAPUA',
    '133' => 'BPD BENGKULU',
    '134' => 'BPD SULAWESI TENGAH',
    '135' => 'BPD SULAWESI TENGGARA',
    '137' => 'BPD BANTEN',
];
